iitbcn/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from organization.views import ValidateStudentVerification, ValidateFacultyVerification

from .views import IndexView
import organization.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^student_validation/(?P<recipient_id>\d+)/$',
        ValidateStudentVerification.as_view(),
        name='student_validation'),
    url(r'^faculty_validation/(?P<recipient_id>\d+)/$',
        ValidateFacultyVerification.as_view(),
        name='faculty_validation'),
    url(r'^profile/', include(organization.urls, namespace='profile')),
]

organization/models/organization.py
from django.contrib.auth.models import User
from django.db import models

from organization.models.utils import OrganizationObjectType, MAX_RECIPIENTS


class StudentLeader(models.Model):
    user = models.ForeignKey(User, related_name='student_leader')
    designation = models.CharField(max_length=128)

    def __str__(self):
        return "{}, {}".format(self.user.get_full_name(), self.designation)


class FacultyInCharge(models.Model):
    user = models.ForeignKey(User, related_name='faculty_in_charge')
    designation = models.CharField(max_length=128)

    def __str__(self):
        return "{name}, {designation}".format(name=self.user.get_full_name(), designation=self.designation)


class Organization(models.Model):
    name = models.CharField(max_length=64)
    student_leader = models.ForeignKey(StudentLeader, related_name='organizations', null=True)
    faculty_incharge = models.ForeignKey(FacultyInCharge, related_name='organizations', null=True)

    def __str__(self):
        return self.name


class OrganizationObject(models.Model):
    name = models.CharField(max_length=64, help_text='Name of post')
    organization = models.ForeignKey(Organization, related_name='posts_and_rewards')
    object_type = models.PositiveSmallIntegerField(choices=OrganizationObjectType.choices(),
                                                   default=OrganizationObjectType.POST)
    max_recipients = models.PositiveIntegerField(default=MAX_RECIPIENTS)

    def __str__(self):
        return "{} - {}".format(self.organization.name, self.name)

    class Meta:
        verbose_name = 'Posts and Awards'
        verbose_name_plural = 'Posts and Awards'
        unique_together = ('name', 'organization')

organization/forms.py
from django import forms

from .models import VerificationChoices


class VerificationForm(forms.Form):
    verification_status = forms.IntegerField(
        widget=forms.Select(
            attrs={
                'class': 'form-control',
            },
            choices=VerificationChoices.choices(),
        )
    )

    citation = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Want to provide some citation?',
            'rows': 3
        }),
        required=False,
    )

    rejection_reason = forms.CharField(
        widget=forms.Textarea(attrs={
            'class': 'form-control',
            'placeholder': 'Why are you rejecting this?',
            'rows': 3
        }),
        required=False,
    )

    signature = forms.BooleanField()

    def clean(self):
        cleaned_data = super().clean()
        verification_status = cleaned_data.get('verification_status')
        citation = cleaned_data.get('citation')
        rejection_reason = cleaned_data.get('rejection_reason')

        if verification_status == VerificationChoices.VERIFIED:
            if rejection_reason:
                raise forms.ValidationError(
                    'Rejection reason is entered for an accepted request'
                )

        elif verification_status == VerificationChoices.REJECTED:
            if not rejection_reason:
                raise forms.ValidationError(
                    'Rejection reason is not entered for a rejected request'
                )
            if citation:
                raise forms.ValidationError(
                    'Citation is entered for a rejected request'
                )

templates/validation/faculty_validation.html
{% extends 'validation/student_validation.html' %}

{% block faculty_block %}
        <div class="form-group">
            <label class="col-sm-2 control-label">Pre-verification By</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    {{ student_verifier.name }} ({{ student_verifier.ldap_username }})
                </p>
            </div>
        </div>

        {% if student_leader_verification.citation %}
            <div class="form-group">
                <label class="col-sm-2 control-label">Citation</label>
                <div class="col-sm-10">
                    <p class="form-control-static">
                        {{ student_leader_verification.citation }}
                    </p>
                </div>
            </div>
        {% endif %}
{% endblock %}

templates/validation/student_validation.html
{% extends 'root.html' %}
{% load staticfiles %}

{% block body %}

    <h3 class="text-capitalize text-center">Verification Request</h3>

    <form class="form-horizontal" method="POST">
        {% csrf_token %}
        <ul class="form-error">
            {% for error in verification_form.non_field_errors %}
                <li><strong>{{ error }}</strong></li>
            {% endfor %}
        </ul>
        <div class="form-group">
            <label class="col-sm-2 control-label">Organization</label>
            <div class="col-sm-10">
                <p class="form-control-static">{{ organization }}</p>
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Object</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    {{ organization_object.name }} ({{ organization_object.get_object_type_display }})
                </p>
            </div>
        </div>
        <div class="form-group">
            <label for="recipient" class="col-sm-2 control-label">Recipient</label>
            <div class="col-sm-10">
                <p class="form-control-static">
                    {{ recipient.user.get_full_name|default:recipient.user.username }}
                </p>
            </div>
        </div>

        {% block faculty_block %}{% endblock %}

        <div class="form-group">
            <label for="id_verification_status" class="col-sm-2 control-label">Choose Status</label>
            <div class="col-sm-3">
                {{ verification_form.verification_status }}
                <ul class="form-error">
                    {% for error in verification_form.verification_status.errors %}
                        <li><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="citation_form_div" class="form-group hide">
            <label for="id_citation" class="col-sm-2 control-label">Citation</label>
            <div class="col-sm-10">
                {{ verification_form.citation }}
                <span class="help-block">Citation will be visible on public certificate</span>
                <ul class="form-error">
                    {% for error in verification_form.citation.errors %}
                        <li><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div id="rejection_reason_form_div" class="form-group hide">
            <label for="id_rejection_reason" class="col-sm-2 control-label">Rejection Reason</label>
            <div class="col-sm-10">
                {{ verification_form.rejection_reason }}
                <span class="help-block">Enter rejection reason only if request is rejected</span>
                <ul class="form-error">
                    {% for error in verification_form.rejection_reason.errors %}
                        <li><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="signature"> I,
                        <b>{{ verifier.name }}</b>
                        as <b>{{ verifier.designation }}</b>
                        hereby confirm that all information is correct as per best of my knowledge
                    </label>
                </div>
                <ul class="form-error">
                    {% for error in verification_form.signature.errors %}
                        <li><strong>{{ error }}</strong></li>
                    {% endfor %}
                </ul>
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </form>

{% endblock %}

{% block jsLinks %}
    <script type="text/javascript">
        var citation_value = "{{ verification_choices.VERIFIED }}";
        var rejection_reason_value = "{{ verification_choices.REJECTED }}";
    </script>

    <script type="text/javascript" src="{% static 'js/validation/validation.js' %}"></script>
{% endblock %}